### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by chhsieh0309** [deepak112/Keras-SRGAN#4]
Hi there,

Do you have any suggestion for the memory usage? I tested your project on a PC with 32GM system memory and dual nVidia RTX 2080Ti but got a OOM failure. How did I tune the the memory usage?

**Comment by deepak112** [comment]
It may be because of following issues-
* Amount of data you are using for training is very large.
* Images size is quite bit. What dimension images are you using?
* Sometimes batch size we choose big, try smaller batch size.
* if above things don't work, try smaller network. Reduce some residual blocks.
